import Head from 'next/head'
import Navbar from '../components/Navbar'
import MovieSearch from '../components/movieSearch'
// import Layout from '../components/Layout'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hypertube</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* <Header /> */}
      <Navbar />

      <main className={styles.main}>
        <h1 className="text-3xl font-bold">Welcome to Hypertube</h1>

        <p className={styles.description}>This is the Main section</p>
        {/* <Body /> */}
				<MovieSearch/>

        <div className={styles.grid}></div>
      </main>

      {/* <Footer /> */}
      <footer className={styles.footer}>All right reserved by @team_hypertube</footer>
    </div>
  )
}
