import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hypertube</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* <Header /> */}

      <main className={styles.main}>
        <h1 className="text-3xl font-bold">Welcome to Hypertube</h1>

        <p className={styles.description}>This is the Main section</p>
        {/* <Body /> */}

        <div className={styles.grid}></div>
      </main>

      <footer className={styles.footer}>
        {/* <Footer /> */}
        All right reserved by @team_hypertube
      </footer>
    </div>
  )
}
